name: New Relic - AWS Logs Ingestion - Pull Request

on: [pull_request]

permissions:
  contents: read

jobs:
  lint:
    strategy:
      matrix:
        python-version: ["3.13"]
        poetry-version: ["1.8.3"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install Project
        run: poetry install --no-interaction
      - name: Lint
        run: |
          poetry run flake8 src test
          poetry run black --check src test

  test:
    strategy:
      matrix:
        python-version: ["3.13"]
        poetry-version: ["1.4"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1
      - name: Install Project
        run: poetry install --no-interaction
      - name: Test
        run: poetry run pytest
